// Code generated by MockGen. DO NOT EDIT.
// Source: tp-db-project/internal/app/forum (interfaces: Repository)

// Package mock_forum is a generated GoMock package.
package mock_forum

import (
	gomock "github.com/golang/mock/gomock"
)

// ForumRepository is a mock of Repository interface.
type ForumRepository struct {
	ctrl     *gomock.Controller
	recorder *ForumRepositoryMockRecorder
}

// ForumRepositoryMockRecorder is the mock recorder for ForumRepository.
type ForumRepositoryMockRecorder struct {
	mock *ForumRepository
}

// NewForumRepository creates a new mock instance.
func NewForumRepository(ctrl *gomock.Controller) *ForumRepository {
	mock := &ForumRepository{ctrl: ctrl}
	mock.recorder = &ForumRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *ForumRepository) EXPECT() *ForumRepositoryMockRecorder {
	return m.recorder
}
