// Code generated by MockGen. DO NOT EDIT.
// Source: tp-db-project/internal/app/forum (interfaces: Usecase)

// Package mock_forum is a generated GoMock package.
package mock_forum

import (
	gomock "github.com/golang/mock/gomock"
)

// ForumUsecase is a mock of Usecase interface.
type ForumUsecase struct {
	ctrl     *gomock.Controller
	recorder *ForumUsecaseMockRecorder
}

// ForumUsecaseMockRecorder is the mock recorder for ForumUsecase.
type ForumUsecaseMockRecorder struct {
	mock *ForumUsecase
}

// NewForumUsecase creates a new mock instance.
func NewForumUsecase(ctrl *gomock.Controller) *ForumUsecase {
	mock := &ForumUsecase{ctrl: ctrl}
	mock.recorder = &ForumUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *ForumUsecase) EXPECT() *ForumUsecaseMockRecorder {
	return m.recorder
}
