// Code generated by MockGen. DO NOT EDIT.
// Source: tp-db-project/internal/app/users (interfaces: Repository)

// Package mock_users is a generated GoMock package.
package mock_users

import (
	gomock "github.com/golang/mock/gomock"
)

// UsersRepository is a mock of Repository interface.
type UsersRepository struct {
	ctrl     *gomock.Controller
	recorder *UsersRepositoryMockRecorder
}

// UsersRepositoryMockRecorder is the mock recorder for UsersRepository.
type UsersRepositoryMockRecorder struct {
	mock *UsersRepository
}

// NewUsersRepository creates a new mock instance.
func NewUsersRepository(ctrl *gomock.Controller) *UsersRepository {
	mock := &UsersRepository{ctrl: ctrl}
	mock.recorder = &UsersRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *UsersRepository) EXPECT() *UsersRepositoryMockRecorder {
	return m.recorder
}
